// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PulseJUA.RatingEngineBDDQATesting.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("PulseJUARatingEngine")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PulseJUARatingEngineFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "PulseJUARatingEngine", "Test the JUA Rating Engine Using BDD and Data Driven Testing", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "PulseJUARatingEngine.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PulseJUARatingEngine.feature.ndjson", 50);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("1-PhysicianSurgeon-Claimsmade")]
        [global::NUnit.Framework.CategoryAttribute("PhysicianSurgeon")]
        [global::NUnit.Framework.CategoryAttribute("ClaimsMade")]
        [global::NUnit.Framework.TestCaseAttribute("\"000003\"", "9799.0", "\"C94FE6C3-9160-4D8F-36B4-08DE38C84580\"", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000004\"", "28844.0", "\"0F499B5E-7CEF-41EC-8459-08DE39C62624\"", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000005\"", "57885.0", "\"252A948C-BA91-4E95-845A-08DE39C62624\"", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000006\"", "43972.0", "\"09728801-2468-4319-845B-08DE39C62624\"", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000007\"", "17542.0", "\"22EA07DC-97BD-45CA-845C-08DE39C62624\"", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000008\"", "31999.0", "\"73E76A79-A87C-4AE4-845D-08DE39C62624\"", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000009\"", "8036.0", "\"BC659C69-EB16-4760-845E-08DE39C62624\"", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000010\"", "67939.0", "\"AAD9A152-6A39-4AFA-845F-08DE39C62624\"", "7", null)]
        public async global::System.Threading.Tasks.Task _1_PhysicianSurgeon_Claimsmade(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PhysicianSurgeon",
                    "ClaimsMade"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1-PhysicianSurgeon-Claimsmade", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("I have a PhysicianSurgeon Application", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category PhysicianS" +
                        "urgeon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
        await testRunner.GivenAsync("Policy type is Claimsmade", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2-PhysicianSurgeon-Occurrence")]
        [global::NUnit.Framework.CategoryAttribute("PhysicianSurgeon")]
        [global::NUnit.Framework.CategoryAttribute("Occurrence")]
        [global::NUnit.Framework.TestCaseAttribute("\"000011\"", "42542.0", "\"BA3C9A21-034C-4968-8460-08DE39C62624\"", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000012\"", "3980.0", "\"07F582E5-475D-4A3E-8461-08DE39C62624\"", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000013\"", "33679.0", "\"496D8AA5-2D8D-4B89-8462-08DE39C62624\"", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000014\"", "10628.0", "\"68034A46-009F-4836-8463-08DE39C62624\"", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000015\"", "112231.0", "\"83DE5157-2B97-4238-8464-08DE39C62624\"", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000016\"", "33323.0", "\"AA8A585A-1890-4BCE-8465-08DE39C62624\"", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000017\"", "14755.0", "\"4AAA2C09-2340-4256-8466-08DE39C62624\"", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000018\"", "19645.0", "\"21B076D9-DE83-49C5-8467-08DE39C62624\"", "15", null)]
        public async global::System.Threading.Tasks.Task _2_PhysicianSurgeon_Occurrence(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PhysicianSurgeon",
                    "Occurrence"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2-PhysicianSurgeon-Occurrence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("I have a PhysicianSurgeon Application", null, tagsOfRule);
#line 29
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category PhysicianS" +
                        "urgeon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
        await testRunner.GivenAsync("Policy type is Occurrence", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("3-HealthCareProfessional-Claimsmade")]
        [global::NUnit.Framework.CategoryAttribute("HealthCareProfessional")]
        [global::NUnit.Framework.CategoryAttribute("ClaimsMade")]
        [global::NUnit.Framework.TestCaseAttribute("\"000019\"", "22225.0", "\"AB52F7BD-4535-4281-8468-08DE39C62624\"", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000020\"", "6948.0", "\"87F4AF12-2EAE-432C-8469-08DE39C62624\"", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000021\"", "19147.0", "\"8341CE50-A286-4936-846A-08DE39C62624\"", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000022\"", "741.0", "\"DD3C60C1-7C98-4A9D-846B-08DE39C62624\"", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000023\"", "2911.0", "\"66145BFE-A167-4248-846C-08DE39C62624\"", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000024\"", "11674.0", "\"8C95CF7D-65CB-4EFE-846D-08DE39C62624\"", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000025\"", "454.0", "\"4D96F0B2-C877-4B90-846E-08DE39C62624\"", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000026\"", "7111.0", "\"C3C0B32F-B4E9-40D3-846F-08DE39C62624\"", "23", null)]
        public async global::System.Threading.Tasks.Task _3_HealthCareProfessional_Claimsmade(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HealthCareProfessional",
                    "ClaimsMade"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3-HealthCareProfessional-Claimsmade", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Medical Insurance Application was created in Pulse JUA with category HealthCare" +
                    "Professional", null, tagsOfRule);
#line 52
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category HealthCare" +
                        "Professional", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
        await testRunner.GivenAsync("Policy type is Claimsmade", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("4-HealthCareProfessional-Occurrence")]
        [global::NUnit.Framework.CategoryAttribute("HealthCareProfessional")]
        [global::NUnit.Framework.CategoryAttribute("Occurrence")]
        [global::NUnit.Framework.TestCaseAttribute("\"000027\"", "170304.0", "\"93A0CFE1-0DC5-4286-8470-08DE39C62624\"", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000028\"", "250.0", "\"5E6DB52A-CEC9-4910-8471-08DE39C62624\"", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000029\"", "8728.0", "\"EE9023F5-B1F2-4878-8472-08DE39C62624\"", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000030\"", "1140.0", "\"E9CDC541-24B3-41A5-8473-08DE39C62624\"", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000031\"", "10097.0", "\"BFD4B9AF-A105-43BC-8474-08DE39C62624\"", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000032\"", "25765.0", "\"8E19EB4E-08FC-4847-8475-08DE39C62624\"", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000033\"", "16176.0", "\"DE589598-EC17-4ECE-8476-08DE39C62624\"", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000034\"", "6512.0", "\"998F4FD7-1E89-4652-8477-08DE39C62624\"", "31", null)]
        public async global::System.Threading.Tasks.Task _4_HealthCareProfessional_Occurrence(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HealthCareProfessional",
                    "Occurrence"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4-HealthCareProfessional-Occurrence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Medical Insurance Application was created in Pulse JUA with category HealthCare" +
                    "Professional", null, tagsOfRule);
#line 70
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category HealthCare" +
                        "Professional", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
        await testRunner.GivenAsync("Policy type is Occurrence", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("5-FacilityAppl-Claimsmade")]
        [global::NUnit.Framework.CategoryAttribute("FacilityAppl")]
        [global::NUnit.Framework.CategoryAttribute("ClaimsMade")]
        [global::NUnit.Framework.TestCaseAttribute("\"000035\"", "293665.0", "\"3B56AC3E-C2D8-4BFF-ABBA-08DE3C16F58B\"", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000036\"", "494363.0", "\"4E029343-302B-4973-ABBB-08DE3C16F58B\"", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000037\"", "1152728.0", "\"440DE8DA-FB2A-4D18-ABBC-08DE3C16F58B\"", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000038\"", "329997.0", "\"C1D1FF7D-23A6-4A2B-ABBD-08DE3C16F58B\"", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000039\"", "441797.0", "\"054B1B7C-941D-4ACA-ABBE-08DE3C16F58B\"", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000040\"", "146969.0", "\"D09A4325-2A44-46A3-ABBF-08DE3C16F58B\"", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000041\"", "859149.0", "\"743386B9-0CA2-44FE-ABC0-08DE3C16F58B\"", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000042\"", "436447.0", "\"2105925A-606E-4F07-ABC1-08DE3C16F58B\"", "39", null)]
        public async global::System.Threading.Tasks.Task _5_FacilityAppl_Claimsmade(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FacilityAppl",
                    "ClaimsMade"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5-FacilityAppl-Claimsmade", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Medical Insurance Application was created in Pulse JUA with category FacilityAp" +
                    "pl", null, tagsOfRule);
#line 93
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category FacilityAp" +
                        "pl", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
        await testRunner.GivenAsync("Policy type is Claimsmade", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("6-FacilityAppl-Occurrence")]
        [global::NUnit.Framework.CategoryAttribute("FacilityAppl")]
        [global::NUnit.Framework.CategoryAttribute("Occurrence")]
        [global::NUnit.Framework.TestCaseAttribute("\"000043\"", "349976.0", "\"E8008350-891C-4877-ABC2-08DE3C16F58B\"", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000044\"", "432568.0", "\"52284B01-BC97-4647-ABC3-08DE3C16F58B\"", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000045\"", "1309682.0", "\"8826C5AC-FF15-43F3-ABC4-08DE3C16F58B\"", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000046\"", "340050.0", "\"5ED666F4-B8C7-40A4-ABC5-08DE3C16F58B\"", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000047\"", "1009820.0", "\"FF1BD7BA-54C3-47C9-ABC6-08DE3C16F58B\"", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000048\"", "519358.0", "\"C252B600-B163-4D45-ABC7-08DE3C16F58B\"", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000049\"", "2045594.0", "\"02145520-557E-4E57-ABC8-08DE3C16F58B\"", "46", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"000050\"", "840879.0", "\"FC9ECF50-14E2-4489-ABC9-08DE3C16F58B\"", "47", null)]
        public async global::System.Threading.Tasks.Task _6_FacilityAppl_Occurrence(string appNo, string expectedPremium, string appId, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FacilityAppl",
                    "Occurrence"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appNo", appNo);
            argumentsOfScenario.Add("expectedPremium", expectedPremium);
            argumentsOfScenario.Add("appId", appId);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("6-FacilityAppl-Occurrence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Medical Insurance Application was created in Pulse JUA with category FacilityAp" +
                    "pl", null, tagsOfRule);
#line 111
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
    await testRunner.GivenAsync("A Medical Insurance Application was created in Pulse JUA with category FacilityAp" +
                        "pl", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
        await testRunner.GivenAsync("Policy type is Occurrence", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
        await testRunner.WhenAsync(string.Format("the Application is Rated with appNo = {0} and appId = {1}", appNo, appId), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
        await testRunner.ThenAsync(string.Format("the calculated Premium for appNo = {0} should be equal to {1}", appNo, expectedPremium), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
