// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PulseJUA.RatingEngineBDDQATesting.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("PulseJUASurveyJSAPIs")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class PulseJUASurveyJSAPIsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "PulseJUASurveyJSAPIs", "Test the Pulse JUA SurveyJS APIs Using BDD and Data Driven Testing", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "PulseJUASurveyJSAPIs.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
#line 6
    await testRunner.GivenAsync("Pulse JUA SurveyJS APIs does Not need Authentication", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync("Response type is <startOfURL>", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.WhenAsync("Middle Of URL = <middleOfURL> And End of URL = <endOfURL> And AuxiliaryDescriptio" +
                    "n = <auxDescription>", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync(@"Expected Status Code should be equal to <expectedStatusCode> And Expected Array should be equal to <expectedArray> And Expected Length should be equal to <expectedLenght> and Expected 1st element should be equal to <expected1st> And Expected Last element should be equal to <expectedLast>", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PulseJUASurveyJSAPIs.feature.ndjson", 17);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("1-Get-Specialties")]
        [global::NUnit.Framework.CategoryAttribute("Specialties")]
        [global::NUnit.Framework.TestCaseAttribute("\"Specialties", "\"\"", "\"\"", "\"All\"", "200", "true", "217", "{\"id\": \"616ffb04-515a-4159-87e0-c8d62bde09ce\",\"name\": \"Active U.S. Military\", \"co" +
            "de\": \"80172A\"}", "{\"id\": \"017111ac-b5a2-4cee-b969-719116ac0039\", \"name\": \"X-Ray Technician\", \"code\"" +
            ": \"80713\"}", "0", null)]
        public async global::System.Threading.Tasks.Task _1_Get_Specialties(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Specialties"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1-Get-Specialties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2-Get-appSpecialties")]
        [global::NUnit.Framework.CategoryAttribute("appSpecialties")]
        [global::NUnit.Framework.TestCaseAttribute("\"uiSectionSpecialties", "\"0c355626-9dfc-4942-a0d0-6ac8673887c8\"", "\"PhysicianInTraining\"", "\"Physician Surgeon\"", "200", "true", "3", "{\"id\": \"35687134-2386-478f-b142-1e228f9e8733\", \"name\": \"Physician In Training - F" +
            "ellow\", \"code\": \"80100C\"}", "{\"id\": \"5d514bed-f305-4d8b-9975-8e3e6f5f5919\", \"name\": \"Physician In Training - R" +
            "esident\", \"code\": \"80100B\"}", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"uiSectionSpecialties", "\"0c355626-9dfc-4942-a0d0-6ac8673887c8\"", "\"NewSpecialties\"", "\"Physician Surgeon\"", "200", "true", "13", "{\"id\": \"3eb6b0df-c988-4bf9-86c4-4897798dfa31\", \"name\": \"Diagnostic X-Ray Tech\", \"" +
            "code\": \"80148C\"}", "{\"id\": \"4fd05efd-d6a2-4b86-b45a-ba4ab55bce72\", \"name\": \"Radioactive Isotopes\", \"c" +
            "ode\": \"80165B\"}", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"uiSectionSpecialties", "\"0c355626-9dfc-4942-a0d0-6ac8673887c8\"", "\"Other\"", "\"Physician Surgeon\"", "200", "true", "101", "{\"id\": \"616ffb04-515a-4159-87e0-c8d62bde09ce\", \"name\": \"Active U.S. Military\", \"c" +
            "ode\": \"80172A\"}", "{\"id\": \"9e71b96f-2e93-492c-8228-d16b984b2e4a\", \"name\": \"Vascular Surgery\", \"code\"" +
            ": \"80146\"}", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"uiSectionSpecialties", "\"1f216994-30d8-4207-aac4-3a6f8b073dac\"", "\"Other\"", "\"Healthcare Professional\"", "404", "false", "10", "{\"response\": \"No Results\"}", "{\"response\": \"No Results\"}", "4", null)]
        public async global::System.Threading.Tasks.Task _2_Get_AppSpecialties(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "appSpecialties"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2-Get-appSpecialties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("3-Get-uiSectionSpecialties")]
        [global::NUnit.Framework.CategoryAttribute("appSpecialties")]
        [global::NUnit.Framework.TestCaseAttribute("\"appSpecialties\"", "\"Facility\"", "\"\"", "\"\"", "200", "true", "217", "{\"id\": \"616ffb04-515a-4159-87e0-c8d62bde09ce\",\"name\": \"Active U.S. Military\", \"co" +
            "de\": \"80172A\"}", "{\"id\": \"11ff9650-82ea-4fa5-9ed3-e6f8476ba219\", \"name\": \"X-Ray Therapy Technician/" +
            "Radiological Physicist\", \"code\": \"80714B\"}", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"appSpecialties\"", "\"HealthcarePro\"", "\"\"", "\"\"", "200", "true", "217", "{\"id\": \"616ffb04-515a-4159-87e0-c8d62bde09ce\",\"name\": \"Active U.S. Military\", \"co" +
            "de\": \"80172A\"}", "{\"id\": \"11ff9650-82ea-4fa5-9ed3-e6f8476ba219\", \"name\": \"X-Ray Therapy Technician/" +
            "Radiological Physicist\", \"code\": \"80714B\"}", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"appSpecialties\"", "\"Physician\"", "\"\"", "\"\"", "200", "true", "217", "{\"id\": \"616ffb04-515a-4159-87e0-c8d62bde09ce\",\"name\": \"Active U.S. Military\", \"co" +
            "de\": \"80172A\"}", "{\"id\": \"11ff9650-82ea-4fa5-9ed3-e6f8476ba219\", \"name\": \"X-Ray Therapy Technician/" +
            "Radiological Physicist\", \"code\": \"80714B\"}", "7", null)]
        public async global::System.Threading.Tasks.Task _3_Get_UiSectionSpecialties(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "appSpecialties"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3-Get-uiSectionSpecialties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("4-Get-CGLItems")]
        [global::NUnit.Framework.CategoryAttribute("CGLItems")]
        [global::NUnit.Framework.TestCaseAttribute("\"CGLItems\"", "\"\"", "\"\"", "\"All\"", "200", "true", "35", "{\"id\": \"7d0113a8-4b39-403a-8146-2f4b2fd2fa10\", \"description\": \"Apartment Building" +
            "\", \"code\": \"60010\", \"cglpBase\": \"Per unit\"}", "{\"id\": \"10ee4b48-a61b-47f7-8caa-ddb496ceeb0c\", \"description\": \"Vacant Land\", \"cod" +
            "e\": \"49451\",        \"cglpBase\": \"Per Acre\"}", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"CGLItems\"", "\"\"", "\"\"", "\"Item 1\"", "200", "true", "1", "{\"id\": \"7d0113a8-4b39-403a-8146-2f4b2fd2fa10\", \"description\": \"Apartment Building" +
            "\", \"code\": \"60010\", \"cglpBase\": \"Per unit\"}", "{\"id\": \"7d0113a8-4b39-403a-8146-2f4b2fd2fa10\", \"description\": \"Apartment Building" +
            "\", \"code\": \"60010\", \"cglpBase\": \"Per unit\"}", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"CGLItems\"", "\"\"", "\"\"", "\"Item N\"", "200", "true", "1", "{\"id\": \"10ee4b48-a61b-47f7-8caa-ddb496ceeb0c\", \"description\": \"Vacant Land\",     " +
            "   \"code\": \"49451\", \"cglpBase\": \"Per Acre\"}", "{\"id\": \"10ee4b48-a61b-47f7-8caa-ddb496ceeb0c\", \"description\": \"Vacant Land\", \"cod" +
            "e\": \"49451\",        \"cglpBase\": \"Per Acre\"}", "10", null)]
        public async global::System.Threading.Tasks.Task _4_Get_CGLItems(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CGLItems"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4-Get-CGLItems", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("5-Get-facilityprofession")]
        [global::NUnit.Framework.CategoryAttribute("facilityprofession")]
        [global::NUnit.Framework.TestCaseAttribute("\"facilityprofession\"", "\"\"", "\"\"", "\"", "200", "true", "21", "{\"id\": \"cce71498-7f78-4b28-b5cb-055416bdbb3f\", \"description\": \"Laboratory Technic" +
            "ians\"}", "{\"id\": \"7ca1129d-75ed-4339-822a-feec8de33247\", \"description\": \"None\"}", "11", null)]
        public async global::System.Threading.Tasks.Task _5_Get_Facilityprofession(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "facilityprofession"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5-Get-facilityprofession", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("6-Get-Limits")]
        [global::NUnit.Framework.CategoryAttribute("Limits")]
        [global::NUnit.Framework.TestCaseAttribute("\"Limits\"", "\"\"", "\"\"", "\"\"", "200", "true", "4", "{\"id\": \"0df31c69-3331-4852-8a2f-2ed566ca6831\", \"limit\": \"$1,000,000/$3,000,000\", " +
            "\"code\": 72}", "{\"id\": \"57d14107-a022-4afb-8d13-fdbff68dc1e9\", \"limit\": \"$1,000,000/$3,000,000\", " +
            "\"code\": 72}", "12", null)]
        public async global::System.Threading.Tasks.Task _6_Get_Limits(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Limits"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("6-Get-Limits", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("7-Get-States")]
        [global::NUnit.Framework.CategoryAttribute("States")]
        [global::NUnit.Framework.TestCaseAttribute("\"States\"", "\"\"", "\"\"", "\"\"", "200", "true", "60", "{\"name\": \"\", \"abbreviation\": \"\"}", "{\"name\": \"Wyoming\", \"abbreviation\": \"WY\"}", "13", null)]
        public async global::System.Threading.Tasks.Task _7_Get_States(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "States"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("7-Get-States", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("8-Get-Zips")]
        [global::NUnit.Framework.CategoryAttribute("Zips")]
        [global::NUnit.Framework.TestCaseAttribute("\"Zips\"", "\"\"", "\"\"", "\"\"", "200", "true", "90", "{\"id\": \"79b53343-a2d5-40ee-8ad0-001b306a87a6\", \"territory\": \"501\", \"zip\": \"02940\"" +
            "}", "{\"id\": \"fd4ef366-1425-42b1-8a26-f38e98c1b200\", \"territory\": \"503\", \"zip\": \"02842\"" +
            "}", "14", null)]
        public async global::System.Threading.Tasks.Task _8_Get_Zips(string startOfURL, string middleOfURL, string endOfURL, string auxDescription, string expectedStatusCode, string expectedArray, string expectedLenght, string expected1St, string expectedLast, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Zips"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("startOfURL", startOfURL);
            argumentsOfScenario.Add("middleOfURL", middleOfURL);
            argumentsOfScenario.Add("endOfURL", endOfURL);
            argumentsOfScenario.Add("auxDescription", auxDescription);
            argumentsOfScenario.Add("expectedStatusCode", expectedStatusCode);
            argumentsOfScenario.Add("expectedArray", expectedArray);
            argumentsOfScenario.Add("expectedLenght", expectedLenght);
            argumentsOfScenario.Add("expected1st", expected1St);
            argumentsOfScenario.Add("expectedLast", expectedLast);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("8-Get-Zips", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
